dataset_root: /disk1/dataset/CSL-Daily_256x256px
dict_path: ./preprocess/phoenix2014/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval_dialogue_tju_QA_eg_signer_slt
evaluation_prefix: dialogue_tju_QA_eg_signer_slt-groundtruth
