dataset_root: /hd3/phoenix2014-release/phoenix-2014-multisigner
dict_path: ./preprocess/phoenix2014/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval_pheonixT
evaluation_prefix: dialogue_pheonix-groundtruth
